DATA_SOURCE:
  EXTRACT_DATA: data_given/wheat.txt


LOAD_DATA:
  RAW_CSV_PATH: data/raw/raw_wheat.csv


PROCESSED_DATA:
  PROCESSED_CSV_PATH: data/processed/process_wheat.csv


SPLIT_DATA:
  TRAIN_CSV_PATH: data/split/train_wheat.csv
  TEST_CSV_PATH: data/split/test_wheat.csv
  TEST_SIZE: 0.2
  RANDOM_STATE: 42


ESTIMATOR:
  TARGET_COL: Target
  QUADRATIC_DISCRIMINANT_ANALYSIS:
    PARAMS:
      REG_PARAM: 0.0
      STORE_COVARIANCE: False
      TOL: 0.0001


MODEL_PATH: saved_artifact/model.pkl
TRANSFORMER_PATH: saved_artifact/transform.pkl
SCHEMA_PATH : saved_artifact/schema.json


REPORTS:
  PARAMS: report/params.json
  SCORES: report/scores.json


